language: python
python:
  - "3.6"      # current default Python on Travis CI
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
  - pip install coveralls
script:
  - coverage rum pytest Tests.py
after_install: 
  - coveralls
