language: python
python:
  - "3.6"      # current default Python on Travis CI
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coveralls
script:
  - pytest Tests.py
  - coverage run CardValidity.py Tests.py
after_install: coveralls