language: python
python:
  - "3.6"      # current default Python on Travis CI
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coveralls
script:
  - py.test Tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_install: 
  - coveralls
